### ISSUE TITLE
Fix invalid example CSS classes

### ISSUE THREAD

**Issue by hanseo0507** [fkhadra/react-toastify-doc#78]
The CSS class code on the example page appears to be invalid.
https://fkhadra.github.io/react-contexify/how-to-style

The class on the example page differs from the css class written in the source code.

```css
/* exmaple class on the example page */

.contexify__item {
    border: 1px solid red; /* Not Working */
}

.contexify_item {
    border: 1px solid red; /* Working */
}
```
